This function allow us to generate a symbols vector, as source to any communication system, either constituted by random symbols from an alphabet or by two phase reversal symbols. 

Output length given by symb x COD_LEN

In [ ]:
# Libraries
import numpy as np

# Parameters
global COD_LEN, PHASE_REVERSAL
COD_LEN = 1 # Different symbols in alphabet.
PHASE_REVERSAL = False

def source(symb = 100):
  if PHASE_REVERSAL == True:
    vct_bitchain = np.tile(np.concatenate((np.tile(0,COD_LEN),np.tile(1,COD_LEN))), symb//2)
  else:
    #np.random.seed(0) # set seed to obtain same pseudo-random vector every time simulation is performed
    vct_bitchain = np.random.randint(0, 2, symb*COD_LEN)
  return vct_bitchain

Use cases

In [ ]:
COD_LEN = 1
PHASE_REVERSAL = False
print(source(symb = 5))

[1 1 0 1 0]


In [ ]:
COD_LEN = 1
PHASE_REVERSAL = False
print(source(symb = 10))

[1 1 0 0 0 0 1 0 1 0]


In [ ]:
COD_LEN = 2
PHASE_REVERSAL = False
print(source(symb = 10)) 

[1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 1]


In [ ]:
COD_LEN = 1
PHASE_REVERSAL = True
print(source(symb = 10))

[0 1 0 1 0 1 0 1 0 1]


In [ ]:
COD_LEN = 2
PHASE_REVERSAL = True
print(source(symb = 10))

[0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]


In [ ]:
COD_LEN = 8
PHASE_REVERSAL = True
print(source(symb = 10))

[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1
 1 1 1 1 1 1]
